import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

import { Button, buttonVariants } from '@/components/ui/button'
import { Menu, Plus, Search } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from '@/components/navbar'
import {
	Sheet,
	SheetContent,
	SheetTitle,
	SheetTrigger,
} from '@/components/ui/sheet'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<header className='fixed top-0 z-50 w-full border-b px-10 py-2 flex justify-between items-center gap-x-10 bg-white'>
					<Link href='/'>
						<Image
							src='/logo.svg'
							alt='logo'
							width={50}
							height={50}
						/>
					</Link>
					<Button
						className='justify-start w-full lg:max-w-lg max-w-sm rounded-full hidden md:flex'
						size='lg'
						variant='secondary'>
						<Search className='mr-2' />
						<p className='text-muted-foreground'>Search MathCom</p>
					</Button>
					<div className='flex gap-x-5 items-center'>
						<Link
							href='/ask'
							className={buttonVariants({
								className:
									'!bg-[#11244DB2] !rounded-full uppercase !hidden sm:!flex !font-bold',
								size: 'lg',
							})}>
							<Plus strokeWidth={4} />
							Ask
						</Link>
						<Button
							size='lg'
							variant='secondary'
							className='rounded-full aspect-square p-0'></Button>
						<Sheet>
							<SheetTrigger className='block sm:hidden'>
								<Button
									asChild
									size='icon'
									variant='link'>
									<Menu className='w-6 h-6' />
								</Button>
							</SheetTrigger>
							<SheetContent>
								<SheetTitle></SheetTitle>
								<Navbar className='px-5 py-8' />
							</SheetContent>
						</Sheet>
					</div>
				</header>
				<Navbar className='fixed z-40 left-0 border-r w-64 h-full bg-white pt-20 px-5 hidden sm:block' />
				{children}
			</body>
		</html>
	)
}
