"use client";

import Image from "next/image";
import React from "react";
import "katex/dist/katex.min.css";
import MarkdownRenderer from "../MarkdownRenderer";

interface PostBodyProps {
  title: string;
  description: string;
  summary?: string;
  imageURL?: string;
  imageURLs?: string[];
  descRef: (el: HTMLDivElement | null) => void;
  getPreviewHtml: (html: string) => string;
}

/**
 * PostBody Component with LaTeX support via Markdown.
 */
export default function PostBody({
  title,
  description,
  summary,
  imageURL,
  imageURLs,
  descRef,
}: PostBodyProps) {
  return (
    <>
      <h1 className="text-lg font-bold mb-4">{title}</h1>

      {/*
        Auto-detect if description is HTML (TipTap) or Markdown (legacy).
        If it starts with '<', treat as HTML; otherwise, treat as Markdown.
      */}
      {description.trim().startsWith('<') ? (
        <div ref={descRef} className="text-sm" dangerouslySetInnerHTML={{ __html: description }} />
      ) : (
        <div ref={descRef} className="text-sm">
          <MarkdownRenderer content={description} />
        </div>
      )}

      {summary && (
        <div className="my-6 p-4 bg-blue-50 border-l-4 border-blue-400 rounded ai-summary-box">
          <div className="font-semibold mb-2">AI Summary</div>
          <MarkdownRenderer content={summary} />
          <div className="mt-2 text-xs text-gray-500">
            <em>Disclaimer: This summary was generated by AI and may contain errors.</em>
          </div>
        </div>
      )}

      {/* Render up to 3 images if imageURLs is present */}
      {Array.isArray(imageURLs) && imageURLs.length > 0 && (
        <div className={`my-5 grid gap-4 ${imageURLs.length > 1 ? 'grid-cols-2 md:grid-cols-3' : ''}`}>
          {imageURLs.map((url, idx) => (
            <div key={idx} className="w-full aspect-video bg-neutral-100 rounded-xl overflow-hidden">
              <Image
                src={url}
                alt={`Uploaded image ${idx + 1}`}
                width={800}
                height={400}
                className="w-full h-full object-cover rounded-xl"
              />
            </div>
          ))}
        </div>
      )}

      {/* Fallback for legacy single imageURL */}
      {!imageURLs && imageURL && (
        <div className="w-full aspect-video bg-neutral-100 rounded-xl my-5">
          <Image
            src={imageURL}
            alt="Uploaded image"
            width={800}
            height={400}
            className="w-full h-full object-cover rounded-xl"
          />
        </div>
      )}
    </>
  );
}
